# history settings
export HISTCONTROL=ignoredups:ignorespace
export HISTFILESIZE=1000
export HISTSIZE=1000

# append to the history file, don't overwrite it
shopt -s histappend

# shell behavior
shopt -s cdspell
shopt -s nocaseglob
shopt -s checkwinsize
shopt -s dotglob
shopt -s extglob

# no core dumps
ulimit -S -c 0

# load aliases
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# load completions from brew installation
if [ -f `brew --prefix`/etc/bash_completion ]; then
    . `brew --prefix`/etc/bash_completion
fi

# activate RVM
[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm

# load prompt
if [ -f ~/.bash_prompt ]; then
    . ~/.bash_prompt
fi

