# history settings
export HISTCONTROL=erasedups
export HISTFILESIZE=10000
export HISTSIZE=${HISTFILESIZE}

# grep settings
export GREP_OPTIONS="--color=auto"
export GREP_COLOR="4;33"

# load completions
source ~/.git_completion.sh
source ~/.bash_completion.sh

# aliases
alias ls="ls -Gh"
alias ll="ls -l"
alias la="ll -a"
alias lt="ll -t"
alias df="df -h"
alias du="du -h"

# confirmations
alias cp="cp -i"
alias rm="rm -i"

# lock screen
alias lock="open /System/Library/Frameworks/ScreenSaver.framework/Versions/A/Resources/ScreenSaverEngine.app"

# RVM aliases
alias rgc="rvm gemset create"
alias rgu="rvm gemset use"

# misc aliases
alias top="top -o cpu"
alias hist="history"
alias showip="ifconfig | grep broadcast | sed 's/.*inet \(.*\) netmask.*/\1/'"

# shell behavior
shopt -s cdspell
shopt -s nocaseglob
shopt -s checkwinsize
shopt -s dotglob
shopt -s extglob
shopt -s progcomp

# no core dumps
ulimit -S -c 0

# reload source
reload() { source ~/.bash_profile; }

# Activate RVM
[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm

# Use global gemset by default
if (command -v rvm > /dev/null) ; then
    rvm gemset use global > /dev/null
fi

# prompt: [user@host] path (branch) [rvm_info]
PS1='\n[\u@\h] \[\033[1;36m\]\w\[\033[0m\]$(__git_ps1 " \[\033[1;31m\](%s)\[\033[0m\]") \[\033[1;34m\][$(rvm-prompt v g)]\[\033[0m\]\n\$ '

