#
# Shell Aliases
#

# MacOS X only aliases
if [ `uname` == "Darwin" ]; then
  alias ls="ls -Gh"
else
  alias ls="ls --color=auto -h"
fi

# Main commands
alias ll="ls -l"
alias la="ll -a"
alias lt="ll -t"

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias df="df -h"
alias du="du -h"

# confirmations
alias cp="cp -i"
alias rm="rm -i"

# misc aliases
alias vi="vim"
alias hist="history"

# for RVM
alias rvu="rvm use"
alias rvg="rvm gemset"
alias rgu="rvg use"
alias rgl="rvg list"
alias rgc="rvg create"
alias rgd="rvg delete"
alias rgg="rgu global"

# for RubyGems
alias gv="gem -v"
alias gl="gem list"
alias gi="gem install"
alias gd="gem uninstall"
alias gc="gem cleanup"
alias gu="gem update"

# for Bundler
alias bi="bundle install"
alias bu="bundle update"
alias be="bundle exec"
alias bp="bundle package"

# Use this to have all the gems and dependancies in the vendor dir of your app
# It's intended to use as an alternative to RVM gemsets
alias binit="bi --path vendor && bp && b --binstubs && echo 'vendor/ruby' >> .gitignore"

# reload shell
alias reload="exec $SHELL"

